// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6XGoABScwX8Bp_xwBXFBzTSdBobYvMdE',
    appId: '1:193227320452:web:37cc006d4fea9bd00066d1',
    messagingSenderId: '193227320452',
    projectId: 'recomendaciones-app',
    authDomain: 'recomendaciones-app.firebaseapp.com',
    storageBucket: 'recomendaciones-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-hEGnFqbayJBgWtb0piy0whTVpLsLpg',
    appId: '1:193227320452:android:241fba5679b435680066d1',
    messagingSenderId: '193227320452',
    projectId: 'recomendaciones-app',
    storageBucket: 'recomendaciones-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxATffkR79At1yfXr452YU4ZAkeAONrR4',
    appId: '1:193227320452:ios:4ab69732be99d6320066d1',
    messagingSenderId: '193227320452',
    projectId: 'recomendaciones-app',
    storageBucket: 'recomendaciones-app.appspot.com',
    iosBundleId: 'com.example.tourbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxATffkR79At1yfXr452YU4ZAkeAONrR4',
    appId: '1:193227320452:ios:401fc035d3a239db0066d1',
    messagingSenderId: '193227320452',
    projectId: 'recomendaciones-app',
    storageBucket: 'recomendaciones-app.appspot.com',
    iosBundleId: 'com.example.tourbuddy.RunnerTests',
  );
}
